Feature/api route
IceStorman/SoftServeProject pull request #3
Opened 2024-11-22 10:36 UTC by Iarynovskyi

added flask-api + cache

2024-11-23 08:29 UTC, Avariq commented on api/routes/__init__.py
> +    app.config['CACHE_DEFAULT_TIMEOUT'] = 300
What are those? seconds? please specify.

If those are 5 minutes, I'd suggest writing 60 * 5 and writing a comment "5 min" or smth

2024-11-23 08:32 UTC, Avariq commented on api/routes/api_games.py
> +       return jsonify({"error": str(e)}), 500
if it's used more than once consider separating it into a different method e.g. "get_error_response" or whatever

2024-11-23 08:35 UTC, Avariq commented on api/routes/api_news.py
> +def make_cache_key():
can we only have one of those decorators in our code? If it serves the exact same purpose as the one in api_games file we should reuse it by moving it to some other place first and then importing wherever needed.

2024-11-23 08:36 UTC, Avariq commented on api/routes/api_teams.py
> +def make_cache_key():
same here

2024-11-23 08:37 UTC, Avariq commented on requirements.txt
> +Flask-Caching~=2.3.0
about damn time

2024-11-23 08:45 UTC, Avariq commented on service/api_logic/news_logic.py
>          print(f"\033[31mNo news was found in the database.\033[0m")
Consider creating separate method "print_text_in_red" (don't copy the method name. It's definitely not what you might want to have) which would handle the coloring of the text. 

Google DRY, YAGNI, KISS and, of course, SOLID.

2024-11-23 08:48 UTC, Avariq commented on service/api_logic/news_logic.py
> +        return {"error": f"Sport '{sport_name}' not found"}
Create logic for proper exception/error handling. Less hardcode.

You might wanna look into "Custom Exceptions" on Google, or at least create a method to form the body of the error

2024-11-23 08:49 UTC, Avariq requested changes
Please fix the issues before merging

2024-11-23 09:02 UTC, Iarynovskyi commented on requirements.txt
> +Flask-Caching~=2.3.0
what's wrong here ?

2024-11-30 20:32 UTC, Avariq commented on api/routes/api_teams.py
> +def make_cache_key():
Probably missed this one :)

2024-11-30 20:34 UTC, Avariq approved these changes
MINOR: api_teams is till declaring "make_cache_key" function.

2024-12-01 07:25 UTC, merged